format = """\
[ÓÇ∂](bg:#030B16 fg:#7DF9AA)\
$custom\
[ÓÇ∞](fg:#7DF9AA bg:#1C3A5E)\
$time\
[ÓÇ∞](fg:#1C3A5E bg:#3B76F0)\
$directory\
[ÓÇ∞](fg:#3B76F0 bg:#EBA1A1)\
$git_branch\
$git_status\
$git_metrics\
[ÓÇ∞](fg:#EBA1A1 bg:#EAC41C)\
$python\
[ÓÇ∞](fg:#EAC41C bg:#030B16)\
$character\
"""
command_timeout=800
[custom.os_icon]
command = """
if [[ "$(uname)" == "Darwin" ]]; then
    printf "Ô£ø"  # Apple icon
elif [[ "$(uname)" == "Linux" ]]; then
    printf "üêß"  # Penguin icon
else
    printf "üíª"  # Default icon for other OS
fi
"""
when = "true"
format = '[$output]($style)'
style = "bg:#7DF9AA fg:#090c0c"

[directory]
format = "[ $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = " ‚õ± "
style = "fg:#1C3A5E bg:#EBA1A1"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#EBA1A1"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#EBA1A1"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[$symbol$branch]($style)"
symbol = "Ôêò "

[cmd_duration]
format = "[ ‚è≤ $duration]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ‚ûú](bold green) '
error_symbol = '[ ‚úó](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ üïë $time](bg:#1C3A5E fg:#8DFBD2)]($style)'

[python]
# The format string determines how the module looks.
# This example shows the symbol, Python version, and the venv name.
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

# The symbol for the Python module. Nerd Fonts offer more options.
symbol = "üêç "

# The style for the Python module.
style = "fg:#555555 bg:#EAC41C"

# The following options control when the module is shown.
# Starship automatically detects if a venv is active and displays its name.
detect_extensions = ["py"]
